sudo: required
dist: xenial
language: 
  - python
  - cpp
python:
  - "3.5.2"
cache: 
  - pip
  - ccache
compiler: 
  - g++
before_install:
  - sudo apt-get update
install:
  - pip install -r ./requirements.txt || travis_terminate 1
  - sudo apt-get install -y xorg-dev libglu1-mesa-dev libpulse-dev || travis_terminate 1
  - sudo apt-get install -y swig || travis_terminate 1
  - sudo apt-get install qt512base qt512svg qt512charts-no-lgpl qt512xmlpatterns qt512multimedia qt512webengine || travis_terminate 1
  - source /opt/qt512/bin/qt512-env.sh || travis_terminate 1
  - sudo apt-get install clang-format || travis_terminate 1
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'ppa:beineri/opt-qt-5.12.3-xenial'
    packages:
      - gcc-6
      - g++-6
script:
  - sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++
  - export CC=/usr/bin/gcc-6
  - export CXX=/usr/bin/g++-6
  - mkdir ../../lib || travis_terminate 1
  - git clone https://github.com/mpromonet/libv4l2cpp ../../lib/libv4l2cpp || travis_terminate 1
  - pushd ../../lib/libv4l2cpp ; make EXTRA_CXXFLAGS='-fPIC' ; popd || travis_terminate 1
  - make || travis_terminate 1
  - pytest -v --cov=./ tests/ || travis_terminate 1
  - cd ./c_plus_plus/ || travis_terminate 1
  - qmake steno.pro -spec linux-g++ CONFIG+=qtquickcompiler || travis_terminate 1
  - make clean || travis_terminate 1
  - make || travis_terminate 1